version: '3'

volumes:
  static_volume:

services:
  django:
    container_name: django
    build: 
      context: .
      dockerfile: docker/django/Dockerfile
    env_file:
      - ./.env
    volumes:
      - static_volume:/app/static
    expose:
      - 8080
    
  nginx:
    container_name: nginx
    build:
      context: docker/nginx/
      dockerfile: Dockerfile
    ports:
      - 8080:80
    depends_on:
      - django
    volumes:
      - static_volume:/app/static